language: python
python:
- '3.8'
stages:
  - lint
  - tests
before_script: |
  pip3 install pipenv
  pipenv lock
  pipenv sync
jobs:
  include:
    - stage: lint
      scripts: |
        pylama .
    - stage: tests
      script: |
        pytest
