language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
stages:
  - lint
  - tests
before_script: |
  pip3 install pipenv
  pipenv lock
  pipenv sync --dev
jobs:
  include:
    - stage: lint
      scripts: pylama .
    - stage: tests
      script: tox
before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
    -in .env.enc -out .env -d
