language: python
python:
- '3.8'
stages:
  - tests
jobs:
  include:
    - stage: tests
      before_script: |
        pip3 install pipenv
        pipenv install --dev
        pipenv shell
      script:
        pytest
